id: P009227
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:28:58.095950
source_metadata:
  id: bdr:W1KG6085
  title: བོད་ལུགས་འབྲས་ནད་གསོ་རིག་
  author: ''
  volumes:
    0b0fb79f3b1b436fa2d2f7317451aeba:
      image_group_id: I1KG6277
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
