id: I00B5E52A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:41:01+00:00'
last_modified: '2022-06-08T09:31:18.191754+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6085
  title: བོད་ལུགས་འབྲས་ནད་གསོ་རིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    7CAA:
      image_group_id: I1KG6277
      title: ''
      total_pages: 224
      order: 1
      base_file: 7CAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
